title: lsb2059
description:  # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" 
url: "https://lsb2059.github.io" 
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Subeen Lee # add your name
author-img: david-freeman.jpg # add your photo
about-author: Uncertainty of Machine Learning # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: lsb2059 # add your Github handle
social-linkedin: Subeen Lee # add your Linkedin handle
social-email: kl2059@hanyang.ac.kr # add your Email address

# Disqus
discus-identifier: lsb2059 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
